### ISSUE TITLE
Specs to be added

### ISSUE THREAD

**Issue by wolfgangmahnke** [iswunistuttgart/opcua-cs-graph#14]
FDI Spec (https://opcfoundation.org/developer-tools/specifications-opc-ua-collaborations/opc-unified-architecture-for-fdi/) [Released]
Commercial Kitchen Devices (https://www.beuth.de/de/technische-regel/din-spec-18898/290190554) (in German, will also be released by OPC Foundation in English) [Released]
VDMA: Robotics and Vision Systems Spec (available as Release Candidate, found no public reference)
OPC UA for IO-Link (Release candidate, found no public reference)

**Comment by Kantiran91** [comment]
The VDMA Robotics and Maschine Vision can be found here:
- https://normung.vdma.org/viewer/-/v2article/render/26810016
- https://normung.vdma.org/viewer/-/v2article/render/26815453

**Comment by fernwerker** [comment]
@digitalshow can you add the mentioned specs, please?

**Comment by Kantiran91** [comment]
I add of this  Companion Specification. So I close the issue
